---
version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    container_name: nginx-proxy

  jupyter:
    image: jupyter/scipy-notebook:17aba6048f44
    command: "start-notebook.sh --NotebookApp.base_url='/apps/jupyter/8888'"
    container_name: jupyter-host

